databases:
  - name: sqlite-site-db
    databaseName: users_db
    user: users_db_user
    plan: free

services:
  - type: web
    name: sqlite-site
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: sqlite-site-db
          property: connectionString